"use client"
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    const jwt_token = localStorage.getItem('jwt_token') || '';

    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
            </head>
            <body data-bs-theme='dark'>
                <header>
                <nav className="navbar bg-body-tertiary">
                    <div className="container-fluid">
                        <a className="navbar-brand">User Posts</a>
                        {!jwt_token ?
                            <ul className='navbar-nav flex-row gap-2'>
                                <li className='nav-item'>
                                    <Link className='btn btn-outline-secondary' href={"/registration"}>Регистрация</Link>
                                </li>
                                <li className='nav-item'>
                                    <Link className='btn btn-primary' href={"/login"}>Авторизация</Link>
                                </li>
                                <li className='nav-item'>
                                    <Link className='btn btn-success' href={"/"}>Главная</Link>
                                </li>
                            </ul>
                            :
                            <ul className='navbar-nav flex-row gap-2'>
                                <li>
                                    <button className='btn btn-outline-secondary' onClick={() => {localStorage.removeItem('jwt_token')}}>Logout</button>
                                </li>
                            </ul>
                        } 
                    </div>
                </nav>
                </header>
                {children}
            </body>
        </html>
    );
}
