import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
            </head>
            <body className={inter.className} data-bs-theme='dark'>
                <header>
                <nav className="navbar bg-body-tertiary">
                    <div className="container-fluid">
                        <a className="navbar-brand">User Posts</a>
                        <ul className='navbar-nav flex-row gap-2'>
                            <li className='nav-item'>
                                <Link className='btn btn-outline-secondary' href={"/registration"}>Регистрация</Link>
                            </li>
                            <li className='nav-item'>
                                <Link className='btn btn-primary' href={"/login"}>Авторизация</Link>
                            </li>
                            <li className='nav-item'>
                                <Link className='btn btn-success' href={"/"}>Главная</Link>
                            </li>
                        </ul>
                    </div>
                </nav>
                    {/* <nav className='d-flex gap-2 p-3'>
                        <Link className='btn btn-outline-secondary' href={"./registration"}>Регистрация</Link>
                        <Link className='btn btn-primary' href={"./login"}>Авторизация</Link>
                    </nav> */}
                </header>
                {children}
            </body>
        </html>
    );
}
